[build-system]
build-backend = "mesonpy"
requires = ["meson-python>=0.15.0"]

[project]
name = "dfanalyzer"
version = "0.1.0"
description = "Analyze, visualize, and understand I/O performance issues in HPC workflows"
authors = [{ name = "Izzet Yildirim", email = "izzetcyildirim@gmail.com" }]
maintainers = [{ name = "Izzet Yildirim", email = "izzetcyildirim@gmail.com" }]
requires-python = ">3.8, <3.12"
readme = { file = "README.md", content-type = "text/markdown" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Build Tools",
    "Typing :: Typed",
]
dependencies = [
    "dask[bag,dataframe,distributed]>=2024.1.0,<2025",
    "dask_jobqueue~=0.8.0",
    "hydra-core~=1.3.0",
    "inflect==7.0",
    "jinja2>=3.0",
    "numpy==1.24.3",
    "matplotlib>=3.6.0",
    "pandas>=2.0",
    "portion>=2.4.0",
    "pyarrow>=13",
    "pyyaml>=5.4",
    "rich==13.6.0",
    "scikit-learn~=1.3.0",
    "scipy~=1.10.0",
    "strenum>=0.4",
    "venn==0.1.3",
    "zindex_py==0.0.5",
]

[project.optional-dependencies]
darshan = ["darshan>=3.4"]

[project.scripts]
dfanalyzer = "dfanalyzer.__main__:main"
dfanalyzer-cluster = "dfanalyzer.cluster:main"
dfanalyzer-plot = "dfanalyzer.plots:main"

[project.urls]
documentation = "https://dfanalyzer.readthedocs.io/en/latest/"
source = "https://github.com/LLNL/dfanalyzer"
tracker = "https://github.com/LLNL/dfanalyzer/issues"

[tool.meson-python.args]
install = ["--skip-subprojects"]

[tool.pyright]
exclude = ["build/", "subprojects/", "tmp/"]

[tool.pytest.ini_options]
markers = [
    "smoke: minimal test subset for quick validation (select with '-m smoke')",
    "full: comprehensive test suite with all parameter combinations (select with '-m full')",
]
filterwarnings = [
    "ignore:The distutils package is deprecated and slated for removal.*:DeprecationWarning",
]

[tool.ruff]
line-length = 119

[tool.ruff.format]
quote-style = "preserve"

[tool.spin]
package = 'dfanalyzer'
